
spring:
  cloud:
    gateway:
      routes:
      - id: service-products
        uri: lb://service-products
        predicates:
          - Path=/api/products/**
        filters:
          - name: CircuitBreaker
            args:
              name: productos
              statusCodes: 500
              fallbackUri: forward:/api/items/ver/9/cantidad/5
          - StripPrefix=2
          - EjemploCookie=Hola mi mensaje personalizado, usuario, AndresGuzman
      - id: service-items
        uri: lb://service-items
        predicates:
          - Path=/api/items/**
        filters:
          - StripPrefix=2
          - AddRequestHeader=token-request, 123456
          - AddResponseHeader=token-response, 12345678
          - SetResponseHeader=Content-Type, text/plain
          - AddRequestParameter = nombre, andres