spring:
  cloud:
    gateway:
      routes:
      - id: service-products
        uri: lb://service-products
        predicates:
          - Path=/api/products/**
        filters:
          - StripPrefix=2
          - name: EjemploCookie
            args:
              cookieMessage: Este Mensaje Proviene Desde APPYML
              cookieName: usuario
              cookieValue: Xalailo
      - id: service-items
        uri: lb://service-items
        predicates:
          - Path=/api/items/**
        filters:
          - StripPrefix=2
#          - name: EjemploGatewayFilterFactory